"""Hardcoded starting links per (sheet, university, program), seeded from the 2025-2026 workbook.

Tracking parameters (utm_*, gclid, ...) were stripped. Keys are lower-cased; an empty program means
"any program of that university on that sheet". Add or fix links here; the agent starts from them
and follows same-site links.
"""

import re

COLLEGE_LINKS: dict[tuple[str, str, str], list[str]] = {
    ('1yr MBA', 'cornell university', ''): ['https://www.johnson.cornell.edu/programs/full-time-mba/cornell-tech-mba/'],
    ('1yr MBA', 'cornell university', 'tech mba'): ['https://www.johnson.cornell.edu/programs/full-time-mba/cornell-tech-mba/'],
    ('1yr MBA', 'new york university', ''): ['https://www.stern.nyu.edu/programs-admissions/luxury-retail-mba'],
    ('1yr MBA', 'new york university', 'mba business: luxury & retail'): ['https://www.stern.nyu.edu/programs-admissions/luxury-retail-mba'],
    ('1yr MBA', 'northwestern university', ''): ['https://www.kellogg.northwestern.edu/programs/full-time-mba/one-year-mba-program/'],
    ('1yr MBA', 'northwestern university', 'one-year mba'): ['https://www.kellogg.northwestern.edu/programs/full-time-mba/one-year-mba-program/'],
    ('1yr MBA', 'pennsylvania state university', ''): ['https://oneyearmba.smeal.psu.edu/'],
    ('1yr MBA', 'pennsylvania state university', 'one-year mba'): ['https://oneyearmba.smeal.psu.edu/'],
    ('1yr MBA', 'purdue university', ''): ['https://business.purdue.edu/master-of-business/one-year-mba/home.php'],
    ('1yr MBA', 'purdue university', 'one-year mba'): ['https://business.purdue.edu/master-of-business/one-year-mba/home.php'],
    ('1yr MBA', 'university of cincinnati', ''): ['https://business.uc.edu/programs-degrees/graduate/mba.html'],
    ('1yr MBA', 'university of cincinnati', 'full-time mba'): ['https://business.uc.edu/programs-degrees/graduate/mba.html'],
    ('1yr MBA', 'university of florida', ''): ['https://warrington.ufl.edu/mba/program-options/full-time-mba/full-time-mba-one-year-all-majors/'],
    ('1yr MBA', 'university of florida', 'full-time mba one-year - all majors'): ['https://warrington.ufl.edu/mba/program-options/full-time-mba/full-time-mba-one-year-all-majors/'],
    ('1yr MBA', 'university of kentucky', ''): ['https://gatton.uky.edu/prc/full-time-mba'],
    ('1yr MBA', 'university of kentucky', 'full-time mba'): ['https://gatton.uky.edu/prc/full-time-mba'],
    ('1yr MBA', 'university of pittsburgh', ''): ['https://business.pitt.edu/mba/accelerated-mba/'],
    ('1yr MBA', 'university of pittsburgh', 'accelerated mba'): ['https://business.pitt.edu/mba/accelerated-mba/'],
    ('MS Accounting - Residential', 'indiana university - bloomington', ''): ['https://kelley.iu.edu/programs/ms-accounting/index.html'],
    ('MS Accounting - Residential', 'indiana university - bloomington', 'master of science in accounting with data and analytics'): ['https://kelley.iu.edu/programs/ms-accounting/index.html'],
    ('MS Accounting - Residential', 'northern illinois university', ''): ['https://www.cob.niu.edu/academics/accountancy/master-of-accounting-science/index.shtml'],
    ('MS Accounting - Residential', 'northern illinois university', 'master of accounting science'): ['https://www.cob.niu.edu/academics/accountancy/master-of-accounting-science/index.shtml'],
    ('MS Accounting - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-accounting/home.php'],
    ('MS Accounting - Residential', 'purdue university', 'master of science in accounting'): ['https://business.purdue.edu/masters/programs/ms-accounting/home.php'],
    ('MS Accounting - Residential', 'university of illinois - urbana champaign', ''): ['https://giesbusiness.illinois.edu/msa'],
    ('MS Accounting - Residential', 'university of illinois - urbana champaign', 'master of science in accountancy'): ['https://giesbusiness.illinois.edu/msa'],
    ('MS Accounting - Residential', 'university of notre dame', ''): ['https://mendoza.nd.edu/graduate-programs/accountancy-msa/'],
    ('MS Accounting - Residential', 'university of notre dame', 'master of science in accountancy'): ['https://mendoza.nd.edu/graduate-programs/accountancy-msa/'],
    ('MS Accounting - Residential', 'university of wisconsin', ''): ['https://business.wisc.edu/graduate/masters/accounting-business-analysis/'],
    ('MS Accounting - Residential', 'university of wisconsin', 'master of science in accounting and business analysis'): ['https://business.wisc.edu/graduate/masters/accounting-business-analysis/'],
    ('MS BAIM - Residential', 'arizona state university', ''): ['https://wpcarey.asu.edu/masters-programs/business-analytics'],
    ('MS BAIM - Residential', 'arizona state university', 'master of science in business analytics'): ['https://wpcarey.asu.edu/masters-programs/business-analytics'],
    ('MS BAIM - Residential', 'georgia institute of technology', ''): ['https://www.analytics.gatech.edu/'],
    ('MS BAIM - Residential', 'georgia institute of technology', 'master of science in analytics'): ['https://www.analytics.gatech.edu/'],
    ('MS BAIM - Residential', 'new york university', ''): ['https://stern.shanghai.nyu.edu/en/program/ms-data-analytics-business-computing'],
    ('MS BAIM - Residential', 'new york university', 'master of science in data analytics and business computing'): ['https://stern.shanghai.nyu.edu/en/program/ms-data-analytics-business-computing'],
    ('MS BAIM - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-business-analytics-and-information-management/home.php'],
    ('MS BAIM - Residential', 'purdue university', 'master of science in business analytics and information management'): ['https://business.purdue.edu/masters/programs/ms-business-analytics-and-information-management/home.php'],
    ('MS BAIM - Residential', 'university of california los angeles', ''): ['https://www.anderson.ucla.edu/degrees/master-of-science-in-business-analytics-msba'],
    ('MS BAIM - Residential', 'university of california los angeles', 'master of science in business analytics'): ['https://www.anderson.ucla.edu/degrees/master-of-science-in-business-analytics-msba'],
    ('MS BAIM - Residential', 'university of minnesota', ''): ['https://carlsonschool.umn.edu/graduate/masters/business-analytics'],
    ('MS BAIM - Residential', 'university of minnesota', 'master of science in business analytics'): ['https://carlsonschool.umn.edu/graduate/masters/business-analytics'],
    ('MS BAIM - Residential', 'university of southern california', ''): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-business-analytics'],
    ('MS BAIM - Residential', 'university of southern california', 'master of science in business analytics'): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-business-analytics'],
    ('MS BAIM - Residential', 'university of texas - austin', ''): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-business-analytics/ms-business-analytics-on-campus/'],
    ('MS BAIM - Residential', 'university of texas - austin', 'master of science in business analytics'): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-business-analytics/ms-business-analytics-on-campus/'],
    ('MS Finance - Residential', 'boston college', ''): ['https://www.bc.edu/bc-web/schools/carroll-school/graduate/ms-programs/ms-in-finance.html'],
    ('MS Finance - Residential', 'boston college', 'ms in finance'): ['https://www.bc.edu/bc-web/schools/carroll-school/graduate/ms-programs/ms-in-finance.html'],
    ('MS Finance - Residential', 'boston university', ''): ['https://www.bu.edu/questrom/graduate-programs/specialty-masters-programs/ms-in-finance/'],
    ('MS Finance - Residential', 'boston university', 'ms in finance'): ['https://www.bu.edu/questrom/graduate-programs/specialty-masters-programs/ms-in-finance/'],
    ('MS Finance - Residential', 'cornell university', ''): ['https://www.engineering.cornell.edu/orie/meng/financial-engineering-concentration/'],
    ('MS Finance - Residential', 'cornell university', 'financial engineering concentration'): ['https://www.engineering.cornell.edu/orie/meng/financial-engineering-concentration/'],
    ('MS Finance - Residential', 'indiana university - bloomington', ''): ['https://academics.iu.edu/degrees/bloomington/master-of-science-in-finance.html'],
    ('MS Finance - Residential', 'indiana university - bloomington', 'master of science in finance'): ['https://academics.iu.edu/degrees/bloomington/master-of-science-in-finance.html'],
    ('MS Finance - Residential', 'johns hopkins university', ''): ['https://carey.jhu.edu/programs/master-science-programs/ms-finance-full-time'],
    ('MS Finance - Residential', 'johns hopkins university', 'master of science in finance'): ['https://carey.jhu.edu/programs/master-science-programs/ms-finance-full-time'],
    ('MS Finance - Residential', 'new york university', ''): ['https://stern.shanghai.nyu.edu/en/program/ms-quantitative-finance'],
    ('MS Finance - Residential', 'new york university', 'ms in quantitative finance'): ['https://stern.shanghai.nyu.edu/en/program/ms-quantitative-finance'],
    ('MS Finance - Residential', 'ohio state university', ''): ['https://fisher.osu.edu/graduate/smf'],
    ('MS Finance - Residential', 'ohio state university', 'specialized master in finance'): ['https://fisher.osu.edu/graduate/smf'],
    ('MS Finance - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-finance/home.php'],
    ('MS Finance - Residential', 'purdue university', 'master of science in finance'): ['https://business.purdue.edu/masters/programs/ms-finance/home.php'],
    ('MS Finance - Residential', 'university of california san diego', ''): ['https://rady.ucsd.edu/programs/master-quantitative-finance/index.html'],
    ('MS Finance - Residential', 'university of california san diego', 'master of quantitative finance'): ['https://rady.ucsd.edu/programs/master-quantitative-finance/index.html'],
    ('MS Finance - Residential', 'university of illinois - urbana champaign', ''): ['https://giesbusiness.illinois.edu/msf'],
    ('MS Finance - Residential', 'university of illinois - urbana champaign', 'master of science in finance'): ['https://giesbusiness.illinois.edu/msf'],
    ('MS Finance - Residential', 'university of southern california', ''): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-finance'],
    ('MS Finance - Residential', 'university of southern california', 'master of science in finance'): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-finance'],
    ('MS Finance - Residential', 'university of texas - austin', ''): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-finance/'],
    ('MS Finance - Residential', 'university of texas - austin', 'master of science in finance'): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-finance/'],
    ('MS Finance - Residential', 'university of wisconsin', ''): ['https://business.wisc.edu/graduate/masters/finance/'],
    ('MS Finance - Residential', 'university of wisconsin', 'master of science in finance, investment and banking'): ['https://business.wisc.edu/graduate/masters/finance/'],
    ('MS GSCM - Residential', 'arizona state university', ''): ['https://wpcarey.asu.edu/masters-programs/supply-chain'],
    ('MS GSCM - Residential', 'arizona state university', 'master of science in supply chain management'): ['https://wpcarey.asu.edu/masters-programs/supply-chain'],
    ('MS GSCM - Residential', 'michigan state university', ''): ['https://broad.msu.edu/masters/supply-chain-management/'],
    ('MS GSCM - Residential', 'michigan state university', 'master of science in supply chain management'): ['https://broad.msu.edu/masters/supply-chain-management/'],
    ('MS GSCM - Residential', 'pennsylvania state university', ''): ['https://mscm.smeal.psu.edu/'],
    ('MS GSCM - Residential', 'pennsylvania state university', 'master of supply chain management'): ['https://mscm.smeal.psu.edu/'],
    ('MS GSCM - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-global-supply-chain-management/home.php'],
    ('MS GSCM - Residential', 'purdue university', 'master of science in global supply chain management'): ['https://business.purdue.edu/masters/programs/ms-global-supply-chain-management/home.php'],
    ('MS GSCM - Residential', 'university of tennessee - knoxville', ''): ['https://haslam.utk.edu/masters/tri-con/'],
    ('MS GSCM - Residential', 'university of tennessee - knoxville', 'master of science in supply chain management tri-continent'): ['https://haslam.utk.edu/masters/tri-con/'],
    ('MS GSCM - Residential', 'university of texas - dallas', ''): ['https://om.utdallas.edu/ms-scm/'],
    ('MS GSCM - Residential', 'university of texas - dallas', 'masters of science in supply chain management'): ['https://om.utdallas.edu/ms-scm/'],
    ('MS GSCM - Residential', 'washington university in st. louis', ''): ['https://olin.wustl.edu/programs/specialized-masters/ms-in-supply-chain-management/index.php'],
    ('MS GSCM - Residential', 'washington university in st. louis', 'master of science in supply chain management'): ['https://olin.wustl.edu/programs/specialized-masters/ms-in-supply-chain-management/index.php'],
    ('MS HRM - Residential', 'ohio state university', ''): ['https://fisher.osu.edu/graduate/mhrm'],
    ('MS HRM - Residential', 'ohio state university', 'master of human resource management'): ['https://fisher.osu.edu/graduate/mhrm'],
    ('MS HRM - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-human-resource-management/home.php'],
    ('MS HRM - Residential', 'purdue university', 'master of human resource management'): ['https://business.purdue.edu/masters/programs/ms-human-resource-management/home.php'],
    ('MS HRM - Residential', 'rutgers university', ''): ['https://smlr.rutgers.edu/academic-programs/graduate-programs/masters-human-resource-management-mhrm'],
    ('MS HRM - Residential', 'rutgers university', 'master of human resource management'): ['https://smlr.rutgers.edu/academic-programs/graduate-programs/masters-human-resource-management-mhrm'],
    ('MS HRM - Residential', 'texas a&m university', ''): ['https://mays.tamu.edu/graduate/masters/ms-programs/human-resource-management/'],
    ('MS HRM - Residential', 'texas a&m university', 'master of science in human resources'): ['https://mays.tamu.edu/graduate/masters/ms-programs/human-resource-management/'],
    ('MS HRM - Residential', 'university of illinois - urbana champaign', ''): ['https://ler.illinois.edu/our-programs/human-resources-masters/'],
    ('MS HRM - Residential', 'university of illinois - urbana champaign', 'master of human resources and industrial relations'): ['https://ler.illinois.edu/our-programs/human-resources-masters/'],
    ('MS HRM - Residential', 'university of minnesota', ''): ['https://carlsonschool.umn.edu/graduate/masters/human-resources-industrial-relations'],
    ('MS HRM - Residential', 'university of minnesota', 'master of human resources & industrial relations'): ['https://carlsonschool.umn.edu/graduate/masters/human-resources-industrial-relations'],
    ('MS HRM - Residential', 'university of south carolina', ''): ['https://www.sc.edu/study/colleges_schools/moore/study/human_resources/degree_programs/master_of_human_resources/index.php'],
    ('MS HRM - Residential', 'university of south carolina', 'master of human resources'): ['https://www.sc.edu/study/colleges_schools/moore/study/human_resources/degree_programs/master_of_human_resources/index.php'],
    ('MS Marketing - Residential', 'babson college', ''): ['https://www.babson.edu/graduate/academics/mba-concentrations/marketing/'],
    ('MS Marketing - Residential', 'babson college', 'mba concentration in marketing (closest degree)'): ['https://www.babson.edu/graduate/academics/mba-concentrations/marketing/'],
    ('MS Marketing - Residential', 'columbia university', ''): ['https://academics.gsb.columbia.edu/msm'],
    ('MS Marketing - Residential', 'columbia university', 'master of science in marketing science'): ['https://academics.gsb.columbia.edu/msm'],
    ('MS Marketing - Residential', 'fordham university', ''): ['https://www.fordham.edu/gabelli-school-of-business/academic-programs-and-admissions/graduate-programs/academic-programs/ms-programs/marketing-intelligence/'],
    ('MS Marketing - Residential', 'fordham university', 'master of science in marketing intelligence'): ['https://www.fordham.edu/gabelli-school-of-business/academic-programs-and-admissions/graduate-programs/academic-programs/ms-programs/marketing-intelligence/'],
    ('MS Marketing - Residential', 'johns hopkins university', ''): ['https://carey.jhu.edu/programs/master-science-programs/ms-marketing-full-time'],
    ('MS Marketing - Residential', 'johns hopkins university', 'master of science in marketing'): ['https://carey.jhu.edu/programs/master-science-programs/ms-marketing-full-time'],
    ('MS Marketing - Residential', 'northwestern university', ''): ['https://www.medill.northwestern.edu/imc/'],
    ('MS Marketing - Residential', 'northwestern university', 'master of science in integrated marketing communications'): ['https://www.medill.northwestern.edu/imc/'],
    ('MS Marketing - Residential', 'purdue university', ''): ['https://business.purdue.edu/masters/programs/ms-marketing/home.php'],
    ('MS Marketing - Residential', 'purdue university', 'master of science in marketing'): ['https://business.purdue.edu/masters/programs/ms-marketing/home.php'],
    ('MS Marketing - Residential', 'university of maryland - college park', ''): ['https://www.rhsmith.umd.edu/programs/business-masters/academics/marketing-analytics'],
    ('MS Marketing - Residential', 'university of maryland - college park', 'master of science in marketing analytics'): ['https://www.rhsmith.umd.edu/programs/business-masters/academics/marketing-analytics'],
    ('MS Marketing - Residential', 'university of rochester', ''): ['https://simon.rochester.edu/programs/full-time-ms-in-marketing-analytics'],
    ('MS Marketing - Residential', 'university of rochester', 'master of science in marketing analytics'): ['https://simon.rochester.edu/programs/full-time-ms-in-marketing-analytics'],
    ('MS Marketing - Residential', 'university of southern california', ''): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-marketing'],
    ('MS Marketing - Residential', 'university of southern california', 'master of science in marketing'): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-marketing'],
    ('MS Marketing - Residential', 'university of texas - austin', ''): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-marketing/'],
    ('MS Marketing - Residential', 'university of texas - austin', 'master of science in marketing'): ['https://www.mccombs.utexas.edu/graduate/specialized-masters/ms-marketing/'],
    ('Master of Business & Technology', 'carnegie mellon university', ''): ['https://www.cmu.edu/tepper/programs/mba/curriculum/concentration/business-technologies.html'],
    ('Master of Business & Technology', 'carnegie mellon university', 'mba business technologies concentration'): ['https://www.cmu.edu/tepper/programs/mba/curriculum/concentration/business-technologies.html'],
    ('Master of Business & Technology', 'columbia university', ''): ['https://sps.columbia.edu/academics/masters/technology-management/master-science'],
    ('Master of Business & Technology', 'columbia university', 'master of science in technology management'): ['https://sps.columbia.edu/academics/masters/technology-management/master-science'],
    ('Master of Business & Technology', 'cornell university', ''): ['https://tech.cornell.edu/programs/masters-programs/johnson-cornell-tech-mba/'],
    ('Master of Business & Technology', 'cornell university', 'johnson cornell tech mba'): ['https://tech.cornell.edu/programs/masters-programs/johnson-cornell-tech-mba/'],
    ('Master of Business & Technology', 'georgia institute of technology', ''): ['https://catalog.gatech.edu/programs/mba-management-technology-executive/'],
    ('Master of Business & Technology', 'georgia institute of technology', 'business administration - management of technology'): ['https://catalog.gatech.edu/programs/mba-management-technology-executive/'],
    ('Master of Business & Technology', 'northwestern university', ''): ['https://www.kellogg.northwestern.edu/programs/full-time-mba/mbai-program.aspx'],
    ('Master of Business & Technology', 'northwestern university', 'mbai program for business & artificial intelligence'): ['https://www.kellogg.northwestern.edu/programs/full-time-mba/mbai-program.aspx'],
    ('Master of Business & Technology', 'purdue university', ''): ['https://business.purdue.edu/master-of-business/master-of-business-and-technology/home.php'],
    ('Master of Business & Technology', 'purdue university', 'master of business and technology'): ['https://business.purdue.edu/master-of-business/master-of-business-and-technology/home.php'],
    ('Online MBA', 'arizona state university', ''): ['https://wpcarey.asu.edu/mba-programs/online'],
    ('Online MBA', 'arizona state university', 'w. p. carey online mba'): ['https://wpcarey.asu.edu/mba-programs/online'],
    ('Online MBA', 'ball state university', ''): ['https://www.bsu.edu/academics/collegesanddepartments/mba/masters-degree'],
    ('Online MBA', 'ball state university', 'online master of business administration'): ['https://www.bsu.edu/academics/collegesanddepartments/mba/masters-degree'],
    ('Online MBA', 'butler university', ''): ['https://www.butler.edu/plus/program/online-mba-program/'],
    ('Online MBA', 'butler university', 'online master of business administration'): ['https://www.butler.edu/plus/program/online-mba-program/'],
    ('Online MBA', 'carnegie mellon university', ''): ['https://www.cmu.edu/tepper/programs/mba/program-options/online-hybrid/index.html'],
    ('Online MBA', 'carnegie mellon university', 'tepper online hybrid mba'): ['https://www.cmu.edu/tepper/programs/mba/program-options/online-hybrid/index.html'],
    ('Online MBA', 'indiana university - bloomington', ''): ['https://kelley.iu.edu/programs/online/index.html'],
    ('Online MBA', 'indiana university - bloomington', 'kelley direct online mba'): ['https://kelley.iu.edu/programs/online/index.html'],
    ('Online MBA', 'purdue university', ''): ['https://business.purdue.edu/master-of-business/online-masters-in-business-administration/overview/home.php'],
    ('Online MBA', 'purdue university', 'purdue online mba'): ['https://business.purdue.edu/master-of-business/online-masters-in-business-administration/overview/home.php'],
    ('Online MBA', 'purdue university global', ''): ['https://www.purdueglobal.edu/degree-programs/business/online-mba-master-business-administration/'],
    ('Online MBA', 'purdue university global', "online master's degree in business administration"): ['https://www.purdueglobal.edu/degree-programs/business/online-mba-master-business-administration/'],
    ('Online MBA', 'rochester institute of technology', ''): ['https://www.rit.edu/study/business-administration-online-executive-mba'],
    ('Online MBA', 'rochester institute of technology', 'business administration–online executive'): ['https://www.rit.edu/study/business-administration-online-executive-mba'],
    ('Online MBA', 'trine university', ''): ['https://www.trine.edu/online/degrees/business-administration/online-mba-master-business-administration.aspx'],
    ('Online MBA', 'trine university', 'online master of business administration'): ['https://www.trine.edu/online/degrees/business-administration/online-mba-master-business-administration.aspx'],
    ('Online MBA', 'university of arizona', ''): ['https://eller.arizona.edu/programs/mba/online'],
    ('Online MBA', 'university of arizona', 'online mba'): ['https://eller.arizona.edu/programs/mba/online'],
    ('Online MBA', 'university of illinois - urbana champaign', ''): ['https://giesonline.illinois.edu/explore-programs/online-mba'],
    ('Online MBA', 'university of illinois - urbana champaign', 'imba (online mba)'): ['https://giesonline.illinois.edu/explore-programs/online-mba'],
    ('Online MBA', 'university of iowa', ''): ['https://tippie.uiowa.edu/iowa-mba'],
    ('Online MBA', 'university of iowa', 'iowa mba'): ['https://tippie.uiowa.edu/iowa-mba'],
    ('Online MBA', 'university of north carolina at chapel hill', ''): ['https://online.unc.edu/online-masters-programs/online-mba/'],
    ('Online MBA', 'university of north carolina at chapel hill', 'unc kenan-flagler’s mba | online'): ['https://online.unc.edu/online-masters-programs/online-mba/'],
    ('Online MBA', 'university of southern california - marshall', ''): ['https://www.marshall.usc.edu/programs/graduate-programs/mba-programs/online-mba'],
    ('Online MBA', 'university of southern california - marshall', 'master of business administration (mba)'): ['https://www.marshall.usc.edu/programs/graduate-programs/mba-programs/online-mba'],
    ('Online MBA', 'university of southern indiana', ''): ['https://online.usi.edu/degrees/business/mba/general/'],
    ('Online MBA', 'university of southern indiana', 'master of business administration online'): ['https://online.usi.edu/degrees/business/mba/general/'],
    ('Online MBA', 'university of texas - dallas', ''): ['https://mba.utdallas.edu/academics/professional-mba-online/'],
    ('Online MBA', 'university of texas - dallas', 'professional mba online'): ['https://mba.utdallas.edu/academics/professional-mba-online/'],
    ('Online MBA', 'university of washington', ''): ['https://foster.uw.edu/academics/degree-programs/hybrid-mba/'],
    ('Online MBA', 'university of washington', 'hybrid mba'): ['https://foster.uw.edu/academics/degree-programs/hybrid-mba/'],
    ('Online MBA', 'university of wisconsin', ''): ['https://www.wisconsinonlinemba.org/'],
    ('Online MBA', 'university of wisconsin', 'mba consortium'): ['https://www.wisconsinonlinemba.org/'],
    ('Online MBA', 'washington university - st. louis', ''): ['https://olin.wustl.edu/programs/mbas/flex-mba/index.php'],
    ('Online MBA', 'washington university - st. louis', 'flex mba'): ['https://olin.wustl.edu/programs/mbas/flex-mba/index.php'],
    ('Online MS Business Analytics', 'ball state university', ''): ['https://www.bsu.edu/academics/collegesanddepartments/online/academic-programs/masters/ms-data-science'],
    ('Online MS Business Analytics', 'ball state university', 'online master of science in data science'): ['https://www.bsu.edu/academics/collegesanddepartments/online/academic-programs/masters/ms-data-science'],
    ('Online MS Business Analytics', 'boston university', ''): ['https://www.bu.edu/met/degrees-certificates/ms-applied-business-analytics/'],
    ('Online MS Business Analytics', 'boston university', 'master of science in applied business analytics'): ['https://www.bu.edu/met/degrees-certificates/ms-applied-business-analytics/'],
    ('Online MS Business Analytics', 'georgetown university', ''): ['https://msb.georgetown.edu/msba/master-of-science-in-business-analytics-online/'],
    ('Online MS Business Analytics', 'georgetown university', 'ms in business analytics (online)'): ['https://msb.georgetown.edu/msba/master-of-science-in-business-analytics-online/'],
    ('Online MS Business Analytics', 'georgia institue of technology', ''): ['https://pe.gatech.edu/degrees/analytics'],
    ('Online MS Business Analytics', 'georgia institue of technology', 'online ms in business analytics (msba)'): ['https://pe.gatech.edu/degrees/analytics'],
    ('Online MS Business Analytics', 'indiana university', ''): ['https://kelley.iu.edu/programs/executive-education-degrees-certificates/online-masters-degrees/business-analytics/index.html'],
    ('Online MS Business Analytics', 'indiana university', 'online ms in business analytics (msba)'): ['https://kelley.iu.edu/programs/executive-education-degrees-certificates/online-masters-degrees/business-analytics/index.html'],
    ('Online MS Business Analytics', 'purdue university', ''): ['https://business.purdue.edu/online/programs/ms-business-analytics/'],
    ('Online MS Business Analytics', 'purdue university', 'online ms business analytics'): ['https://business.purdue.edu/online/programs/ms-business-analytics/'],
    ('Online MS Business Analytics', 'rutgers university', ''): ['https://business.camden.rutgers.edu/graduate/ms-in-business-analytics/'],
    ('Online MS Business Analytics', 'rutgers university', 'master of science in business analytics'): ['https://business.camden.rutgers.edu/graduate/ms-in-business-analytics/'],
    ('Online MS Business Analytics', 'southern illinois university', ''): ['https://onlinedegrees.siu.edu/online/bus-all-sap1-230104/?lsid=google&lssid=siu_all_all_x_sr_gen&groupid=163010202920&campid=21154911326&type=p&network=g&adid=695601446588&ptid=&ad_pos=&fdid=&tgid=kwd-2294181698600&lphys=9016722&linst=&model=&sitetarg='],
    ('Online MS Business Analytics', 'southern illinois university', 'master of science in business analytics'): ['https://onlinedegrees.siu.edu/online/bus-all-sap1-230104/?lsid=google&lssid=siu_all_all_x_sr_gen&groupid=163010202920&campid=21154911326&type=p&network=g&adid=695601446588&ptid=&ad_pos=&fdid=&tgid=kwd-2294181698600&lphys=9016722&linst=&model=&sitetarg='],
    ('Online MS Business Analytics', 'stevens institute of technology', ''): ['https://www.stevens.edu/program/business-intelligence-analytics-masters-program'],
    ('Online MS Business Analytics', 'stevens institute of technology', 'master of science in business intelligence and analytics'): ['https://www.stevens.edu/program/business-intelligence-analytics-masters-program'],
    ('Online MS Business Analytics', 'texas a&m university - college station', ''): ['https://mays.tamu.edu/graduate/masters/ms-programs/analytics/'],
    ('Online MS Business Analytics', 'texas a&m university - college station', 'master of science in analytics'): ['https://mays.tamu.edu/graduate/masters/ms-programs/analytics/'],
    ('Online MS Business Analytics', 'the ohio state university', ''): ['https://online.osu.edu/masters-degree/master-business-analytics'],
    ('Online MS Business Analytics', 'the ohio state university', 'specialized master in business analytics'): ['https://online.osu.edu/masters-degree/master-business-analytics'],
    ('Online MS Business Analytics', 'university of iowa', ''): ['https://tippie.uiowa.edu/masters-business-analytics?creative=649012853754&keyword=%2Biowa+%2Bms+%2Banalytics&matchtype=b&network=g&page=where_in_the_world'],
    ('Online MS Business Analytics', 'university of iowa', 'master of business analytics programs'): ['https://tippie.uiowa.edu/masters-business-analytics?creative=649012853754&keyword=%2Biowa+%2Bms+%2Banalytics&matchtype=b&network=g&page=where_in_the_world'],
    ('Online MS Business Analytics', 'university of michigan', ''): ['https://michiganross.umich.edu/graduate/master-of-business-analytics'],
    ('Online MS Business Analytics', 'university of michigan', 'master of business analytics (mban) program'): ['https://michiganross.umich.edu/graduate/master-of-business-analytics'],
    ('Online MS Business Analytics', 'university of pennsylvania', ''): ['https://online.seas.upenn.edu/degrees/mcit-online/'],
    ('Online MS Business Analytics', 'university of pennsylvania', 'master of computer and information technology'): ['https://online.seas.upenn.edu/degrees/mcit-online/'],
    ('Online MS Economics', 'american university', ''): ['https://programs.online.american.edu/econ/masters-economics'],
    ('Online MS Economics', 'american university', 'ma in economics'): ['https://programs.online.american.edu/econ/masters-economics'],
    ('Online MS Economics', 'george mason university', ''): ['https://masononline.gmu.edu/programs/ma-masters-economics/'],
    ('Online MS Economics', 'george mason university', 'ma in economics'): ['https://masononline.gmu.edu/programs/ma-masters-economics/'],
    ('Online MS Economics', 'georgia southern university', ''): ['https://www.georgiasouthern.edu/cogs/admission/msa/'],
    ('Online MS Economics', 'georgia southern university', 'master of science in applied economics'): ['https://www.georgiasouthern.edu/cogs/admission/msa/'],
    ('Online MS Economics', 'johns hopkins university', ''): ['https://landing.advanced.jhu.edu/applied-economics/'],
    ('Online MS Economics', 'johns hopkins university', 'master of science in applied economics'): ['https://landing.advanced.jhu.edu/applied-economics/'],
    ('Online MS Economics', 'purdue university', ''): ['https://business.purdue.edu/online/programs/ms-economics/'],
    ('Online MS Economics', 'purdue university', 'online ms economics'): ['https://business.purdue.edu/online/programs/ms-economics/'],
    ('Online MS Economics', 'southern new hampshire university', ''): ['https://www.collegefactual.com/graduate-schools/southern-new-hampshire-university/masters-degrees/social-sciences/economics/'],
    ('Online MS Economics', 'southern new hampshire university', "master's in economics"): ['https://www.collegefactual.com/graduate-schools/southern-new-hampshire-university/masters-degrees/social-sciences/economics/'],
    ('Online MS Economics', 'university of detroit mercy', ''): ['https://chass.udmercy.edu/academics/econ/master-of-arts-in-economics.php'],
    ('Online MS Economics', 'university of detroit mercy', 'master of arts in economics'): ['https://chass.udmercy.edu/academics/econ/master-of-arts-in-economics.php'],
    ('Online MS Economics', 'university of missouri-columbia', ''): ['https://online.missouri.edu/degrees-programs/mu/arts-and-sciences/economics/ma'],
    ('Online MS Economics', 'university of missouri-columbia', 'ma in economics'): ['https://online.missouri.edu/degrees-programs/mu/arts-and-sciences/economics/ma'],
    ('Online MS Economics', 'university of north dakota', ''): ['https://und.edu/programs/applied-economics-ms/index.html'],
    ('Online MS Economics', 'university of north dakota', 'master of science in applied economics & predictive analytics'): ['https://und.edu/programs/applied-economics-ms/index.html'],
    ('Online MS HRM', 'florida international university', ''): ['https://business.fiu.edu/academics/graduate/human-resource-management-online/index.html'],
    ('Online MS HRM', 'florida international university', 'master of science in human resource management'): ['https://business.fiu.edu/academics/graduate/human-resource-management-online/index.html'],
    ('Online MS HRM', 'george washington university', ''): ['https://business.gwu.edu/ms-human-resource-management'],
    ('Online MS HRM', 'george washington university', 'master of human resource management (mhrm)'): ['https://business.gwu.edu/ms-human-resource-management'],
    ('Online MS HRM', 'michigan state university', ''): ['https://hrlr.msu.edu/degrees/mhrlr/index.html'],
    ('Online MS HRM', 'michigan state university', 'college of social science'): ['https://hrlr.msu.edu/degrees/mhrlr/index.html'],
    ('Online MS HRM', 'pennsylvania state university', ''): ['https://www.worldcampus.psu.edu/degrees-and-certificates/penn-state-online-human-resources-and-employment-relations-masters-degree'],
    ('Online MS HRM', 'pennsylvania state university', 'master of human resources and employment relations'): ['https://www.worldcampus.psu.edu/degrees-and-certificates/penn-state-online-human-resources-and-employment-relations-masters-degree'],
    ('Online MS HRM', 'pepperdine university', ''): ['https://bschool.pepperdine.edu/online-masters-human-resources/'],
    ('Online MS HRM', 'pepperdine university', "online master's in human resources"): ['https://bschool.pepperdine.edu/online-masters-human-resources/'],
    ('Online MS HRM', 'purdue university', ''): ['https://business.purdue.edu/online/programs/ms-human-resource-management/'],
    ('Online MS HRM', 'purdue university', "online master's in human resource management"): ['https://business.purdue.edu/online/programs/ms-human-resource-management/'],
    ('Online MS HRM', 'purdue university global', ''): ['https://www.purdueglobal.edu/degree-programs/business/online-master-management-degree/'],
    ('Online MS HRM', 'purdue university global', 'online master of science degree in management and leadership'): ['https://www.purdueglobal.edu/degree-programs/business/online-master-management-degree/'],
    ('Online MS HRM', 'rutgers university', ''): ['https://smlr.rutgers.edu/academic-programs/graduate-programs/online-professional-masters-human-resource-management-mhrm'],
    ('Online MS HRM', 'rutgers university', "online professional master's in human resource management (mhrm)"): ['https://smlr.rutgers.edu/academic-programs/graduate-programs/online-professional-masters-human-resource-management-mhrm'],
    ('Online MS HRM', 'stony brook university', ''): ['https://www.stonybrook.edu/commcms/online-masters-in-human-resource-management/index.php'],
    ('Online MS HRM', 'stony brook university', "online master's in human resource management"): ['https://www.stonybrook.edu/commcms/online-masters-in-human-resource-management/index.php'],
    ('Online MS HRM', 'temple university', ''): ['https://www.temple.edu/academics/degree-programs/human-resource-management-ms-bu-hrm-ms'],
    ('Online MS HRM', 'temple university', 'master of science in human resource management'): ['https://www.temple.edu/academics/degree-programs/human-resource-management-ms-bu-hrm-ms'],
    ('Online MS HRM', 'texas a&m', ''): ['https://mays.tamu.edu/graduate/flex-online/human-resource-management/program-details/'],
    ('Online MS HRM', 'texas a&m', 'online ms human resource management'): ['https://mays.tamu.edu/graduate/flex-online/human-resource-management/program-details/'],
    ('Online MS HRM', 'university of connecticut', ''): ['https://hrm.business.uconn.edu/programs/hrm-online-ms-degree/'],
    ('Online MS HRM', 'university of connecticut', 'ms in human resources'): ['https://hrm.business.uconn.edu/programs/hrm-online-ms-degree/'],
    ('Online MS HRM', 'university of illinois urbana-champaign', ''): ['https://online.illinois.edu/online-programs/graduate-programs/human-resources-industrial-relations'],
    ('Online MS HRM', 'university of illinois urbana-champaign', 'master of human resources and industrial relations'): ['https://online.illinois.edu/online-programs/graduate-programs/human-resources-industrial-relations'],
    ('Online MS HRM', 'university of southern california', ''): ['https://bovardcollege.usc.edu/hr/admissions/tuition-financial-aid/'],
    ('Online MS HRM', 'university of southern california', 'online ms in human resource management'): ['https://bovardcollege.usc.edu/hr/admissions/tuition-financial-aid/'],
    ('Online MSGSCM', 'arizona state university', ''): ['https://asuonline.asu.edu/online-degree-programs/graduate/supply-chain-management-ms/'],
    ('Online MSGSCM', 'arizona state university', 'online master of science in supply chain management'): ['https://asuonline.asu.edu/online-degree-programs/graduate/supply-chain-management-ms/'],
    ('Online MSGSCM', 'auburn university', ''): ['https://harbert.auburn.edu/degrees-programs/graduate/ms-supply-chain-online/index.html'],
    ('Online MSGSCM', 'auburn university', 'master of science in supply chain management—online'): ['https://harbert.auburn.edu/degrees-programs/graduate/ms-supply-chain-online/index.html'],
    ('Online MSGSCM', 'boston university', ''): ['https://www.bu.edu/online/programs/graduate-programs/supply-chain-management/'],
    ('Online MSGSCM', 'boston university', 'online master of science in supply chain management degree'): ['https://www.bu.edu/online/programs/graduate-programs/supply-chain-management/'],
    ('Online MSGSCM', 'georgetown university', ''): ['https://scs.georgetown.edu/programs/503/online/online-masters-in-supply-chain-management/'],
    ('Online MSGSCM', 'georgetown university', "online master's in supply chain management"): ['https://scs.georgetown.edu/programs/503/online/online-masters-in-supply-chain-management/'],
    ('Online MSGSCM', 'michigan state university', ''): ['https://explore.michiganstateuniversityonline.com/ms-scm'],
    ('Online MSGSCM', 'michigan state university', 'master of science in supply chain management'): ['https://explore.michiganstateuniversityonline.com/ms-scm'],
    ('Online MSGSCM', 'pennsylvania state university--world campus', ''): ['https://www.worldcampus.psu.edu/degrees-and-certificates/penn-state-online-supply-chain-management-masters-degree'],
    ('Online MSGSCM', 'pennsylvania state university--world campus', 'master of supply chain management'): ['https://www.worldcampus.psu.edu/degrees-and-certificates/penn-state-online-supply-chain-management-masters-degree'],
    ('Online MSGSCM', 'purdue university', ''): ['https://business.purdue.edu/online/programs/ms-global-supply-chain-management/'],
    ('Online MSGSCM', 'purdue university', 'online ms global supply chain management'): ['https://business.purdue.edu/online/programs/ms-global-supply-chain-management/'],
    ('Online MSGSCM', 'rutgers university', ''): ['https://www.business.rutgers.edu/masters-supply-chain-management'],
    ('Online MSGSCM', 'rutgers university', 'master of supply chain management'): ['https://www.business.rutgers.edu/masters-supply-chain-management'],
    ('Online MSGSCM', 'university of kentucky', ''): ['http://online.uky.edu/masters/supply-chain-management/ms'],
    ('Online MSGSCM', 'university of kentucky', 'master’s degree in supply chain management'): ['http://online.uky.edu/masters/supply-chain-management/ms'],
    ('Online MSGSCM', 'university of nebraska-lincoln', ''): ['https://online.unl.edu/major/graduate/master-supply-chain-management/'],
    ('Online MSGSCM', 'university of nebraska-lincoln', 'master of science in supply chain management'): ['https://online.unl.edu/major/graduate/master-supply-chain-management/'],
    ('Online MSGSCM', 'university of southern california', ''): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-global-supply-chain-management'],
    ('Online MSGSCM', 'university of southern california', 'master of science in global supply chain management'): ['https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-global-supply-chain-management'],
    ('Online MSGSCM', 'university of st. francis', ''): ['https://stfrancis.edu/mba/'],
    ('Online MSGSCM', 'university of st. francis', 'mba with supply chain concentration'): ['https://stfrancis.edu/mba/'],
    ('Online MSGSCM', 'university of tenessee-knoxville', ''): ['https://volsonline.utk.edu/program/masters/supply-chain-management-ms/'],
    ('Online MSGSCM', 'university of tenessee-knoxville', 'master’s degree in supply chain management'): ['https://volsonline.utk.edu/program/masters/supply-chain-management-ms/'],
    # From research/link_discovery (high confidence; the automated reachability check had rejected it).
    ('Online MS Economics', 'university of maryland-college park', ''): ['https://masters.econ.umd.edu/online-program/'],
}

# Rows whose university offers no online version of the program (research/link_discovery, 2026-09-19).
# The run fills these rows with "No online program offered" and puts the note in the cell comment.
NO_ONLINE_PROGRAM: dict[tuple[str, str], str] = {
    ('Online MBA', 'georgia institute of technology'): 'Scheller College of Business offers Full-time, Evening and Executive MBAs; no fully online MBA.',
    ('Online MBA', 'university of california-san diego'): 'Rady offers Full-Time, FlexEvening and FlexWeekend (hybrid) MBAs; no fully online MBA.',
    ('Online MS Business Analytics', 'university of california-los angeles'): "UCLA Anderson's MSBA is a 15-month full-time on-campus program; no online format.",
    ('Online MS Business Analytics', 'university of california-san diego'): 'Rady MSBA is full-time on campus (FlexWeekend is in person); no online format.',
    ('Online MS Economics', 'duke university'): 'No online MS in Economics at Duke; its economics master\'s programs are on campus.',
    ('Online MS Economics', 'pennsylvania state university'): 'No online MS in Economics at Penn State; residential MA/PhD in Economics only.',
}


def _norm(s) -> str:
    """Case, punctuation and spacing don't matter; "The X" = "X"; "Texas at Austin" = "Texas - Austin";
    "- West Lafayette" is Purdue's campus tag."""
    words = re.sub(r"[^a-z0-9&]+", " ", str(s).casefold().replace("- west lafayette", "")).split()
    words = [w for w in words if w != "at"]
    return " ".join(words[1:] if words[:1] == ["the"] else words)


_INDEX: dict[tuple[str, str, str], list[str]] = {}
for (_sheet, _college, _program), _urls in COLLEGE_LINKS.items():
    _INDEX.setdefault((_sheet, _norm(_college), _norm(_program)), _urls)


def no_online_program(sheet: str, college: str) -> str | None:
    return next((note for (sh, c), note in NO_ONLINE_PROGRAM.items() if sh == sheet and _norm(c) == _norm(college)), None)


def links_for(sheet: str, college: str, program: str = "") -> list[str]:
    """Exact (sheet, college, program) match first, then any link for the college on that sheet."""
    for prog in (_norm(program), ""):
        urls = _INDEX.get((sheet, _norm(college), prog))
        if urls:
            return urls
    return []
